feat: refactor cicd sample and update to CDK Pipelines
aws-samples/baseline-environment-on-aws pull request #50
Opened 2022-05-18 06:35 UTC by wmikuriy

The CICD sample code was refactored to the implementation by CDK Pipelines, and the code structure was updated to conform to the current CDK practices.

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT No Attribution (MIT-0)].

[MIT No Attribution (MIT-0)]: https://github.com/aws/mit-0

2022-05-20 11:52 UTC, konokenj requested changes
コード内のレビューコメントをご参照ください。英語のMarkdownには注釈を入れていません。日本語へのフィードバックにあわせて英語も修正してください。

2022-05-20 11:52 UTC, konokenj commented on doc/PipelineDeployment_ja.md
> +   ![BLEA-Deploy-2-ChooseGitHub](images/BLEA-Deploy-2-ChooseGitHub.png)
箇条書きのインラインで画像を挿入するのは避けてください。代わりに段落を使用します。

2022-05-20 11:52 UTC, konokenj commented on doc/PipelineDeployment_ja.md
> +4. `GitHub` を選択して、`Connection name` を指定し、 `Connect to GitHub`をクリックします
この記法は必須ではありませんが、バッククォート1つによるインラインコードは、入力値やコードスニペット、IDなどに使用してください。クリックする要素を強調する目的では使用しないでください。代わりに太字にしたり、`[ ]` でくくったりすることが考えられます。

2022-05-20 11:52 UTC, konokenj commented on doc/PipelineDeployment_ja.md
> +8. 以上で Connection の ARN が画面に表示されます。形式は次のとおりです。 "arn:aws:codestar-connections:ap-northeast-1:xxxxxxxxxxxx:connection/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" 後に使用するため、これをコピーします
ここでは逆に Arnをバッククォートで囲むべきです。

2022-05-20 11:52 UTC, konokenj commented on doc/PipelineDeployment_ja.md
> +## 2. CDK Pipelines プロジェクトを設定する
「cdk.jsonに Connection の情報を設定する」など、より具体的に操作を示します。

2022-05-20 11:52 UTC, konokenj commented on doc/PipelineDeployment_ja.md
> +CodePipeline が自身の BLEA リポジトリの対象ブランチにアクセスできるようにするため、デプロイするアプリケーションの cdk.json ファイルを編集する。
コンテキスト情報にアクセスする主体はCodePipelineではなく、CDKです。CDKがこれを読んで、CodePipelineの設定値として引き渡しています。

「デプロイするアプリケーションの cdk.json ファイル」とは具体的にどのパスのファイルですか？

2022-05-20 11:52 UTC, konokenj commented on doc/PipelineDeployment_ja.md
> +- `prodpipeline`: このあと CDK コマンドラインで指定する環境名。このサンプルの場合は `-c environment=prodpipeline` のように指定することになる
`prodpipeline` という値は設定の中にありません。

2022-05-20 11:52 UTC, konokenj commented on doc/PipelineDeployment_ja.md
> +- `env`: パイプラインと BLEA リソースのデプロイターゲットとなるアカウントとリージョン。 Tools アカウントと異なるアカウントにデプロイする場合、デプロイ先のアカウントであらかじめ Bootstrapping と、Tools アカウントの信頼を設定する必要がある。
Bootstrappingだけでは慣れていないとわかりません。AWSドキュメントへのリンクを貼るか、`cdk bootstrap`が必要と書くほうが親切です。

2022-05-20 11:52 UTC, konokenj commented on doc/PipelineDeployment_ja.md
> +- `envName`: 環境名の解説。デプロイ対象のリソースタグに付与される
このあたりの項目はCDK Pipelinesには直接関係なく、READMEに書かれているので、ここでは言及しなくて良いです。

2022-05-20 11:52 UTC, konokenj commented on doc/PipelineDeployment_ja.md
> +- `githubRepository`: GitHub リポジトリの名前。自身のリポジトリ URL が 'https://github.com/ownername/repositoryname.git' である場合、`ownername/repositoryname` を指定する
Connectionが必ずしもGitHubとは限らないため、このキーは妥当ではないです。 `repository`, `branch`, `connectionArn` などはどうでしょうか。

2022-05-20 11:52 UTC, konokenj commented on doc/PipelineDeployment_ja.md
> +- `prodEnv`: Tools アカウントにおけるパイプラインによってデプロイされるスタックのデプロイ先となるアカウント（以下、Prod アカウント（ID: `333333333333`））及びリージョン
`toolEnv`, `prodEnv` も上記にありません。

2022-05-20 11:52 UTC, konokenj commented on doc/PipelineDeployment_ja.md
> +前提：Prod アカウントが Organization に登録されていて、SSO を用いて Credential を取得することができる。
前提であれば「〜こと」で終わるべきです。

2022-05-20 11:52 UTC, konokenj commented on doc/PipelineDeployment_ja.md
> +現在 `guest-webapp-sample/blea-guest-ecsapp-sample.ts` をパイプライン `guest-webapp-sample/blea-guest-ecsapp-sample-pipeline.ts` からデプロイするサンプルが実装されている。これをデプロイする際には以下の手順を実施する。
ここだけですます調じゃなくなっています。

2022-05-20 11:52 UTC, konokenj commented on doc/PipelineDeployment_ja.md
> +現在 `guest-webapp-sample/blea-guest-ecsapp-sample.ts` をパイプライン `guest-webapp-sample/blea-guest-ecsapp-sample-pipeline.ts` からデプロイするサンプルが実装されている。これをデプロイする際には以下の手順を実施する。
あと、このパスあってますか？

2022-05-20 11:52 UTC, konokenj commented on doc/PipelineDeployment_ja.md
> +`cdk build` あるいは `cdk deploy` されるファイルは `cdk.json` で指定するか、各コマンドを実行する際に `-a` オプションで指定することができます。例えば、現在実装されているサンプルパイプラインをデプロイしてみる場合、以下のように設定を書き換える必要があります。
`cdk build` というコマンドはありません。 `cdk synth` ですかね？

2022-05-20 11:52 UTC, konokenj commented on doc/PipelineDeployment_ja.md
> +`cdk build` あるいは `cdk deploy` されるファイルは `cdk.json` で指定するか、各コマンドを実行する際に `-a` オプションで指定することができます。例えば、現在実装されているサンプルパイプラインをデプロイしてみる場合、以下のように設定を書き換える必要があります。
`-a` オプションは cdk.json に書かれた `app` をオーバーライドする効果があります。`-a` を使うならcdk.jsonを変更しなくて良いです。このユースケースを今後はCDK Pipelinesを使ってデプロイし続けるのであれば、都度`-a`を指定するよりcdk.jsonに書いたほうがよいです。この選択肢を書いてほしいです。

オプションをドキュメント上表記する場合はロングオプション `--app` のほうが読みやすいです。

2022-05-20 11:52 UTC, konokenj commented on doc/PipelineDeployment_ja.md
> +`'npm run synth:dev',` の部分を実体に即した synth コマンドに書き換えるか、または以下のように `package.json` で定義される scripts にデプロイパイプラインに即した Synth コマンドを追記・上書きすることも可能です。
実体→実態

2022-05-20 11:52 UTC, konokenj commented on doc/PipelineDeployment_ja.md
> +#### **`usecases/guest-webapp-sample/blea-ecsapp-sample-pipeline-stack.ts`**
libが抜けていますか？

2022-05-20 11:52 UTC, konokenj commented on doc/PipelineDeployment_ja.md
> +`'npm run synth:dev',` の部分を実体に即した synth コマンドに書き換えるか、または以下のように `package.json` で定義される scripts にデプロイパイプラインに即した Synth コマンドを追記・上書きすることも可能です。
`npm run` で実行されるのは package.json の `scripts` に書かれたコマンドなので、どちらを変更しても良いという意味ですね。npmに慣れていない人にはこのつながりが読み取れないため、補足を入れてください。

2022-05-20 11:52 UTC, konokenj commented on doc/PipelineDeployment_ja.md
> +`'npm run synth:dev',` の部分を実体に即した synth コマンドに書き換えるか、または以下のように `package.json` で定義される scripts にデプロイパイプラインに即した Synth コマンドを追記・上書きすることも可能です。
そもそも、なぜこの変更が必要なのでしょう？そして正しい設定はどのようにあるべきですか？

2022-05-20 11:52 UTC, konokenj commented on doc/PipelineDeployment_ja.md
> +> Notes: synth コマンドを実行する際にオプションとして --profile を指定する必要はありません。CodeBuild は適切な権限( Tools アカウントの Administrator 権限)を保持しているためです。
この説明はローカルで`npm run`した場合に誤りとなります。CodeBuild上で呼ばれた場合と両方を考慮してください。

2022-05-20 11:52 UTC, konokenj commented on doc/PipelineDeployment_ja.md
> +### 3.3. 以下のコマンドによってパイプラインを Tools アカウントにデプロイする
タイトルに「以下のコマンド」とポインタを使わず、具体的に内容を示してください。

2022-05-20 11:52 UTC, konokenj commented on doc/PipelineDeployment_ja.md
> +以下のコマンドをローカル環境から実行することで、サンプルパイプラインを Tools アカウントにデプロイすることができます。
パイプライン自体がサンプルなんでしょうか？正しいパイプラインにするには、どうしたらよいですか？

2022-05-20 11:52 UTC, konokenj commented on doc/PipelineDeployment_ja.md
> +## 4. BLEA のコードをアップデートおよびマージすることで、デプロイを実行する
変更をpushすることによってデプロイが実行されることを確認する、ということですね。マージは必ずしも必要ありません。

2022-05-20 11:52 UTC, konokenj commented on doc/PipelineDeployment_ja.md
> +BLEA のコードを変更して、commit し、対象ブランチへのマージを実行します。
マージは必ずしも必要ありません。

2022-05-20 11:52 UTC, konokenj commented on doc/PipelineDeployment_ja.md
> +GitHub に変更が push されたら、CodePipeline プロジェクトが起動され、その中で CodeBuild が実行されます。CodeBuild はご自身の GitHub リポジトリから BLEA ソースコードを取得し、CloudFormation テンプレートを synth した後に、デプロイします。
- GitHubと限定せず、Gitリポジトリと表記してください
- CodePipelineにプロジェクトというリソースはありません
- ソースを取得するのはCodeBuildではなくCodePipelineです
- synthによって作られるのはCFnテンプレートではなく、Cloud Assemblyです

2022-05-20 11:52 UTC, konokenj commented on doc/PipelineDeployment_ja.md
> +以上で BLEA のコードがパイプラインを通じてデプロイされました。
デプロイされたのは、BLEAのコードではなく単一のCDKアプリケーション（ユースケース）です。

2022-05-20 11:52 UTC, konokenj commented on doc/PipelineDeployment_ja.md
> +> Notes: CDK Pipelines では、 [SelfMutation](https://aws.amazon.com/jp/blogs/news/deploying-a-cdk-application-using-the-cdk-pipelines-modern-api/) という機能を使用することで、デプロイパイプラインもレポジトリの更新に応じて継続的にデプロイすることが可能です。
- レポジトリ→リポジトリ
- 「技術的には可能」という表現はドキュメント内では使わないでください。できるか、できないかです
- selfMutationが無効なのですか？

2022-05-20 11:52 UTC, konokenj commented on doc/PipelineDeployment_ja.md
> +<!-- # Appendix.1 - コンテナイメージのデプロイの流れ
ここはなぜコメントアウトされているのでしょうか？いらないのであれば消してください。

2022-05-20 11:52 UTC, konokenj commented on doc/PipelineDeployment_ja.md
> +GitHub に Dockerfile を push します。GitHub Actions でビルドを実行し、本番環境の ECR へイメージを push します。
このサンプルコードがないのであれば、ここに書くべきではありません。

2022-05-20 11:52 UTC, konokenj commented on doc/PipelineDeployment_ja.md
> +実際にシステムを CDK を用いて開発する際には、パイプラインを介さずにスタックをデプロイして検証サイクルを短くすることが必要になることがあります。そのような場合は開発環境用のアカウントに向けて、パイプラインではなくパイプラインによってデプロイされるスタックそのものをデプロイすることも可能です。
パイプライン経由ではなく、特定のスタックを直接デプロイ。ただしこれは本番では使わないように注釈してください。

2022-05-20 11:52 UTC, konokenj commented on doc/PipelineDeployment_ja.md
> +前提：以下に示されているような形で開発環境用に払い出されたアカウント（以下、Dev アカウント（ID: `xxxxxxxxxxxx`））が、Organization に登録されていて、SSO 経由で Credential を取得することができる。
〜こと

2022-05-20 11:52 UTC, konokenj commented on doc/PipelineDeployment_ja.md
> +## 開発環境に対して Stage スタックを直接デプロイする
Stageはスタックではありません。別のクラスです。

2022-05-20 11:52 UTC, konokenj commented on usecases/guest-webapp-sample/pipeline/blea-ecsapp-sample-pipeline-stack.ts
> +      // selfMutation: false,
`pipelineName`は `selfMutation` の設定によらず、未設定にしておくことを推奨します。また、 `selfMutation` はデフォルトで有効で、積極的に無効化すべきではありません。この一連のコメントを削除することを推奨します。

2022-05-20 11:52 UTC, konokenj commented on usecases/guest-webapp-sample/pipeline/blea-ecsapp-sample-pipeline-stack.ts
> +          'npm i -g npm@8.3',
`npm@8.3` の指定はいらなくなっています。

2022-05-20 11:52 UTC, konokenj commented on usecases/guest-webapp-sample/pipeline/blea-ecsapp-sample-pipeline-stack.ts
> +          'echo $account_id',
この `echo` は必要ですか？

2022-05-20 11:52 UTC, konokenj commented on usecases/guest-webapp-sample/pipeline/blea-ecsapp-sample-pipeline-stack.ts
> +          // move to repository to be deployed by this pipeline
意味が通りません。`cd`は自明なのでいらないと思います。

2022-05-20 11:52 UTC, konokenj commented on usecases/guest-webapp-sample/pipeline/blea-ecsapp-sample-pipeline-stack.ts
> +          // 'npm run',
これは無効なコードですし、コメント不要です。

2022-05-20 11:52 UTC, konokenj commented on usecases/guest-webapp-sample/pipeline/blea-ecsapp-sample-pipeline-stack.ts
> +          // 'ls cdk.out',
テスト用でしょうか？

2022-05-20 11:52 UTC, konokenj commented on usecases/guest-webapp-sample/pipeline/blea-ecsapp-sample-pipeline-stack.ts
> +          'npx cdk ls -c environment=dev',
環境名をリテラルで渡してしまっています。これだと、環境を変えるごとにこのスタックをコピーする必要があります。

2022-05-20 11:52 UTC, konokenj commented on usecases/guest-webapp-sample/pipeline/blea-ecsapp-sample-pipeline-stack.ts
> +              value: this.region,
同一リージョン指定の妥当性がわかりません。説明いただけますか？

2022-05-20 11:52 UTC, konokenj commented on usecases/guest-webapp-sample/bin/blea-guest-ecsapp-sample-pipeline.ts
> +function getProcEnv() {
ESLintの警告通り、使わないなら消してください。

2022-05-20 11:52 UTC, konokenj commented on usecases/guest-webapp-sample/bin/blea-guest-ecsapp-sample-pipeline.ts
> +      // getProcEnv should be called in pipeline layer and do not call this func in stage stack.
このコメントを毎回入れる必要はありません。

2022-05-20 11:52 UTC, konokenj commented on usecases/guest-webapp-sample/bin/blea-guest-ecsapp-sample-pipeline.ts
> +      repositoryName: 'apprepo',
TODOが残っているのはなぜですか？

2022-05-20 11:52 UTC, konokenj commented on usecases/guest-webapp-sample/bin/blea-guest-ecsapp-sample-pipeline.ts
> +// You can deploy development stacks.
このコメントの意味がわかりません。

2022-05-20 11:52 UTC, konokenj commented on usecases/guest-webapp-sample/bin/blea-guest-ecsapp-sample-pipeline.ts
> +new BLEAPipelineStack(app, `${pjPrefix}-Prod-Pipeline`, {
環境別にパイプラインを定義していることをコメントしてください。

2022-05-20 11:52 UTC, konokenj commented on usecases/guest-webapp-sample/bin/blea-guest-ecsapp-sample-pipeline.ts
> +  githubTargetBranch: envVals['githubTargetBranchProd'],
別でもコメントしましたが、リポジトリはGitHubとは限らないのでこのキーは変更してください。

2022-05-20 11:52 UTC, konokenj commented on usecases/guest-webapp-sample/bin/blea-guest-ecsapp-sample-pipeline.ts
> +  // If yod don't specify env, stacks will be deployed to Tools Account.
typo

2022-05-20 11:52 UTC, konokenj commented on usecases/guest-webapp-sample/cdk.json
> +  "app": "npx ts-node --prefer-ts-exts bin/blea-guest-ecsapp-sample-pipeline.ts",
この変更を取り込むと、デフォルトでこのユースケースをCDK Pipelinesでデプロイすることになります。今回はそれを意図した修正ではありませんので、もとに戻してください。

2022-05-20 11:52 UTC, konokenj commented on usecases/guest-webapp-sample/package.json
> +    "synth_dev_context_test": "npx cdk synth -c",
これはなんですか？必要でしょうか？

2022-05-21 04:34 UTC, mickn-space commented on doc/PipelineDeployment_ja.md
> +ユースケースサンプルとして提供されている CDK アプリケーションは GitHub に置かれた Baseline Environment on AWS (BLEA) CDK Pipelines によるパイプラインをデプロイします。
Done

2022-05-21 05:45 UTC, wmikuriy commented on doc/PipelineDeployment_ja.md
> +- パイプラインのデプロイ先のアカウント（以下、 Tools アカウント（ID: `222222222222`））およびリージョンで CDK をブートストラップ済みであること
レビューいただいた図でいう1枚目（セットアップ）と2枚目（Toolsアカウントへのデプロイ）が可能で、Optionalで示している作業を行うことで4枚目（Prodに対するクロスアカウントデプロイ）を行うことができます。

2022-05-21 05:52 UTC, wmikuriy commented on doc/PipelineDeployment_ja.md
> +- Tools アカウントに Administrator 権限でアクセスする認証情報を AWS CLI プロファイルとして設定済みであること
[CDK Pipelinesのsrc](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/pipelines) にて、以下の記載がありました。
> Security tip: we recommend that you use administrative credentials to an account only to bootstrap it and provision the initial pipeline. Otherwise, access to administrative credentials should be dropped as soon as possible.

今回のドキュメントのスコープはパイプラインのデプロイなので、ドキュメント中でAdminは終始要求される権限となります。Documentの末尾にデプロイが終わった後はAdmin権限は外しましょうという文言を追記しておきます。

2022-05-21 06:43 UTC, wmikuriy commented on doc/PipelineDeployment_ja.md
> +- `prodEnv`: Tools アカウントにおけるパイプラインによってデプロイされるスタックのデプロイ先となるアカウント（以下、Prod アカウント（ID: `333333333333`））及びリージョン
この項目解説の前のJSONサンプルに書いていないということでしょうか？　追記しました。

2022-05-21 08:03 UTC, wmikuriy commented on doc/PipelineDeployment_ja.md
> +> Notes: CDK Pipelines では、 [SelfMutation](https://aws.amazon.com/jp/blogs/news/deploying-a-cdk-application-using-the-cdk-pipelines-modern-api/) という機能を使用することで、デプロイパイプラインもレポジトリの更新に応じて継続的にデプロイすることが可能です。
現在、SelfMutationは有効化されています。誤っているので削除しました。

2022-05-21 08:45 UTC, wmikuriy commented on doc/PipelineDeployment_ja.md
> +CodePipeline が自身の BLEA リポジトリの対象ブランチにアクセスできるようにするため、デプロイするアプリケーションの cdk.json ファイルを編集する。
今回だと、`usecases/guest-webapp-sample/cdk.json` ですね。分かりやすくなるようにパスを追記して修正しました。

2022-05-23 04:38 UTC, wmikuriy commented on doc/PipelineDeployment_ja.md
> +- Tools アカウントに Administrator 権限でアクセスする認証情報を AWS CLI プロファイルとして設定済みであること
実質Docと同じ内容なので、Docをポインタする

2022-05-23 07:24 UTC, wmikuriy commented on usecases/guest-webapp-sample/bin/blea-guest-ecsapp-sample-pipeline.ts
> +      repositoryName: 'apprepo',
こちらは、コピー元の　blea-guest-ecsapp-sample.ts で残っているTODOになります。

2022-05-26 06:00 UTC, wmikuriy commented on usecases/guest-webapp-sample/pipeline/blea-ecsapp-sample-pipeline-stack.ts
> +              value: this.region,
旧版のコードを流用していた部分ですが、該当部分を外しても問題なく動作しました。修正版では一旦削除しておきます。

2022-05-27 02:03 UTC, wmikuriy commented on usecases/guest-webapp-sample/package.json
> +    "synth_dev_context_test": "npx cdk synth -c",
不要なので削除しました

2022-05-31 11:32 UTC, konokenj requested changes
コメントをご確認ください。多くの差分にsuggestionを入れているので、内容を確認して問題なければ受け入れてください。

2022-05-31 11:32 UTC, konokenj commented on doc/PipelineDeployment.md
> +As an example of CI/CD with CDK, this document shows how to use sample to deploy CDK Application via CDK pipelines.
```suggestion
As an example of CI/CD with CDK, this document shows how to use sample to deploy CDK Application via CDK Pipelines.
```

2022-05-31 13:08 UTC, wmikuriy commented on doc/PipelineDeployment_ja.md
> +複数アカウントにアプリケーションをデプロイする方法は複数ありますが、ここでは一例として、各アカウントごとにパイプラインを作成している例を示しています。この構成は、各アカウントごとに構成 ② で要求される作業を実施することで検証可能です。
古い言及のままでした。構成Bを言及するように修正します

2022-05-31 13:27 UTC, wmikuriy commented on doc/PipelineDeployment_ja.md
> +デフォルトの設定値は `dev` となっていますが、デプロイ先の環境を変更したい場合は適宜 Context の環境名を指定してください。
はい、記述が前の部分と冗長だったのでまとめておきます

2022-06-01 08:09 UTC, merged