feat: introduce knip
aws-samples/baseline-environment-on-aws pull request #924
Opened 2024-12-01 05:17 UTC by Konippi

# Introduce knip for detecting unused exports and dependencies

This PR made it possible for detecting unused exports and dependencies by using [knip](https://knip.dev/).
Here is what I am hoping to achieve by this.

- Reduce security risks by removing unnecessary dependencies
- Incorporate knip into the CI workflow prevents the introduction of unnecessary code and dependencies

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT No Attribution (MIT-0)].

[MIT No Attribution (MIT-0)]: https://github.com/aws/mit-0

2024-12-02 15:11 UTC, Konippi commented
PRs created by `dependabot` will be merged into the main branch in the future, resulting in Conflict due to dependencies.
So, when this PR is approved, I'm going to rebase and consolidate the commits into one.

2024-12-09 01:45 UTC, konokenj requested changes
Thank you for your contribution. I agree that using Knip would provide a better development experience. However, please check the review comments as we need to follow certain CDK conventions.

Actually, we were considering removing depcheck because it required explicitly declaring libraries that were considered to be in use. While Knip seems to eliminate this hassle, we need to support users who aren't familiar with TypeScript. 

Do you think they might find it difficult when encountering Knip errors? If so, we'd like to explain how to handle such situations.

2024-12-09 01:45 UTC, konokenj commented on knip.config.ts
I think this can be set up simply as follows. Especially in CDK, Props types should be exported. These warnings can be suppressed with `ignoreExportsUsedInFile`.

Also, I noticed that there are unused errors in parameter.ts. Since this should be fixed in the future, I wrote a FIXME comment. How does this look?

```typescript
import { KnipConfig } from 'knip';

export default {
  ignoreBinaries: ['git-secrets'],
  ignoreDependencies: ['simple-git-hooks', 'ts-node', 'esbuild'],
  ignoreExportsUsedInFile: true,
  workspaces: {
    'usecases/*': {
      entry: ['bin/*.ts', 'lambda/**/*.{js,ts}'],
      project: '**/*.{js,ts}',
      ignore: ['parameter.ts'], // FIXME: Ignore to avoid unused errors on 'stagingParameter'. We should use all sample values.
    },
  },
} as const satisfies KnipConfig;

```

2024-12-09 01:45 UTC, konokenj commented on usecases/blea-gov-base-ct/lib/construct/detection.ts
> +interface DetectionProps {
As I mentioned above, this should be exported.

2024-12-09 01:45 UTC, konokenj commented on usecases/blea-gov-base-ct/package.json
> -    "prettier": "^3.4.1",
Indeed, while eslint and prettier are only included in the tasks in the project root's package.json and might seem removable, users might want to use eslint and prettier commands when they cd into individual workspaces for development. In such cases, would it be appropriate to remove these dependencies from the workspaces? I'd like to hear your thoughts on this.

2024-12-09 01:45 UTC, konokenj commented on usecases/blea-gov-base-standalone/package.json
> -    "cdk": "cdk"
Please do not delete this. Since it is included in CDK by default, there may be users who want to run `npm run cdk`.

2024-12-09 02:47 UTC, Konippi commented on usecases/blea-gov-base-standalone/package.json
> -    "cdk": "cdk"
There is no doubt! I'll revert this changes.

2024-12-09 02:57 UTC, Konippi commented on knip.config.ts
Thank you for your suggestion.
I guess the config I created was too redundant...
I also forgot that we need to export the type of props.
And I think your suggested comments are great.

2024-12-09 12:14 UTC, Konippi commented on usecases/blea-gov-base-ct/package.json
> -    "prettier": "^3.4.1",
I think developers should be able to`cd` directly to a specific workspace and run lint (`eslint`) and formatting (`prettier`) commands. So, the `eslint` and `prettier` commands should be made available to each workspace.

2024-12-10 04:20 UTC, konokenj approved these changes
Thank you simplifying. I removed prettier and eslint from each usecase with adding a commit. This is because these configuration files exists only in the project root and not in each usecase.

2024-12-10 04:24 UTC, merged